/**
 * NO BYTE SNAPSHOTS. A snapshot of a PDF churns on every pdfkit patch, every font re-instancing and
 * every copy edit, and no reviewer can read the diff. The assertions below are structural: the header
 * and trailer, the page count the pure planner predicts, a byte-size band that catches both "the fonts
 * failed to embed" and "subsetting is off", and the Info dictionary, which is the only reliable TEXT
 * hook because body text is written with subset glyph ids.
 */

import { describe, expect, it } from "vitest"
import { FONT, fontFor } from "../../src/services/certificate-fonts.js"
import { planPages } from "../../src/services/certificate-layout.js"
import {
  buildTranscriptModel,
  type CertificateTranslator,
  type TranscriptLedgerRow,
} from "../../src/services/certificate-model.js"
import { buildServiceHoursPdf } from "../../src/services/certificate-pdf.js"

const CODE = "A1B2C3D4E5F6"
const DISPLAY_CODE = "CFX-A1B2-C3D4-E5F6"
const ISSUED_AT = new Date("2026-07-27T18:22:04.000Z")

/** English-shaped fixture copy, so the assertions do not depend on the locale catalog. */
const t: CertificateTranslator = (key, vars) => {
  switch (key) {
    case "certificate.doc.pdf_title":
      return `civfix service hours — ${String(vars?.name)} — ${String(vars?.code)}`
    case "certificate.doc.title":
      return "Record of Volunteer Service"
    case "certificate.attestation.body":
      return "This record was generated by civfix from its volunteer-service ledger. Hours for an event are entered by that event's host, who must be an identity-verified organizer and who cannot credit hours to themselves."
    case "certificate.table.truncated":
      return `Showing the ${String(vars?.shown)} most recent of ${String(vars?.total)} activities.`
    case "certificate.footer.page":
      return `Page ${String(vars?.page)} of ${String(vars?.total)}`
    default:
      return key.split(".").at(-1) ?? key
  }
}

const HOLDER = {
  userId: "11111111-1111-4111-8111-111111111111",
  displayName: "Jane Doe",
  handle: "jane",
  verified: true,
}

function ledger(count: number, over: Partial<TranscriptLedgerRow> = {}): TranscriptLedgerRow[] {
  return Array.from({ length: count }, (_, i) => ({
    id: `row-${String(i).padStart(5, "0")}`,
    source: "event" as const,
    hours: 2.5,
    occurredAt: new Date(Date.UTC(2026, 0, 1) + i * 86_400_000).toISOString(),
    eventTitle: "Beach cleanup at the pier",
    jurisdictionName: "Los Angeles",
    creditedByName: "Ada Host",
    ...over,
  }))
}

function render(count: number, over: Partial<TranscriptLedgerRow> = {}, locale = "en") {
  const model = buildTranscriptModel({ holder: HOLDER, locale, t, rows: ledger(count, over) })
  return buildServiceHoursPdf({
    model,
    code: CODE,
    issuedAt: ISSUED_AT,
    fingerprint: "f".repeat(64),
    t,
  })
}

/** `/Type /Page` occurrences, excluding `/Type /Pages` (the tree node). */
function pageCount(bytes: Uint8Array): number {
  return (
    Buffer.from(bytes)
      .toString("latin1")
      .match(/\/Type \/Page(?!s)/g) ?? []
  ).length
}

/**
 * How pdfkit writes a PDF text string: ASCII stays a literal, anything else becomes UTF-16BE behind a
 * BOM. The ko fixture is what exercises the second branch (a raw utf8 grep would silently never match).
 */
function pdfString(value: string): Buffer {
  const ascii = [...value].every((ch) => {
    const code = ch.codePointAt(0) ?? 0
    return code >= 0x20 && code <= 0x7e
  })
  if (ascii) return Buffer.from(value, "latin1")
  return Buffer.concat([Buffer.from([0xfe, 0xff]), Buffer.from(value, "utf16le").swap16()])
}

describe("buildServiceHoursPdf", () => {
  it("emits a well-formed PDF 1.7 document", async () => {
    const bytes = await render(3)
    expect(Buffer.from(bytes.subarray(0, 8)).toString("latin1")).toBe("%PDF-1.7")
    expect(Buffer.from(bytes.subarray(-32)).toString("latin1")).toContain("%%EOF")
  })

  it("fits a short transcript, totals and the issuer block on one page", async () => {
    const bytes = await render(3)
    expect(pageCount(bytes)).toBe(1)
    expect(planPages([21, 21, 21])).toHaveLength(1)
  })

  it("paginates a 40-row transcript exactly as planPages predicts, plus the issuer page", async () => {
    const bytes = await render(40)
    // A single-line Activity cell measures somewhere in the 20-22pt band; planPages gives the SAME
    // answer across that whole band, so the prediction is exact without re-measuring here.
    const low = planPages(Array.from({ length: 40 }, () => 20)).length
    const high = planPages(Array.from({ length: 40 }, () => 22)).length
    expect(low).toBe(high)
    // + 1: with 40 rows the last page has under 180pt left, so the issuer block is forced onto its own.
    expect(pageCount(bytes)).toBe(low + 1)
  })

  it("keeps a 40-row document inside the plausible byte band", async () => {
    const bytes = await render(40)
    // Below 15 KB means the fonts did not embed; above 500 KB means subsetting is off.
    expect(bytes.length).toBeGreaterThan(15_000)
    expect(bytes.length).toBeLessThan(500_000)
  })

  it("grows with the ledger and still paginates a long one", async () => {
    const small = await render(40)
    const large = await render(250)
    expect(large.length).toBeGreaterThan(small.length)
    expect(pageCount(large)).toBeGreaterThanOrEqual(9)
  })

  it("renders an empty ledger rather than throwing (the 409 is the service's call, not the renderer's)", async () => {
    const bytes = await render(0)
    expect(pageCount(bytes)).toBe(1)
  })

  it("renders the truncation banner over a capped ledger", async () => {
    const model = buildTranscriptModel({ holder: HOLDER, locale: "en", t, rows: ledger(1005) })
    expect(model.truncated).toBe(true)
    const bytes = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    expect(pageCount(bytes)).toBeGreaterThan(30)
  })

  it("exposes the display code and the holder name through the Info dictionary", async () => {
    const bytes = await render(3)
    const buf = Buffer.from(bytes)
    // /Keywords
    expect(buf.includes(pdfString(DISPLAY_CODE))).toBe(true)
    // /Title
    expect(buf.includes(pdfString(`civfix service hours — Jane Doe — ${DISPLAY_CODE}`))).toBe(true)
  })

  it("writes a non-ASCII Title as UTF-16BE behind a BOM", async () => {
    const model = buildTranscriptModel({
      holder: { ...HOLDER, displayName: "홍길동" },
      locale: "ko",
      t,
      rows: ledger(2, {
        eventTitle: "강남구 정화 활동",
        jurisdictionName: "강남구",
        creditedByName: "김호스트",
      }),
    })
    const bytes = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    const buf = Buffer.from(bytes)
    expect(buf.includes(pdfString(`civfix service hours — 홍길동 — ${DISPLAY_CODE}`))).toBe(true)
  })

  it("renders a Hangul transcript without throwing (the lazy CJK registration path)", async () => {
    const model = buildTranscriptModel({
      holder: { ...HOLDER, displayName: "홍길동", handle: null },
      locale: "ko",
      t,
      rows: ledger(3, {
        eventTitle: "강남구 정화 활동",
        jurisdictionName: "강남구",
        creditedByName: "김호스트",
      }),
    })
    const bytes = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    expect(pageCount(bytes)).toBeGreaterThanOrEqual(1)
    // The Korean face is ~4.6 MB before subsetting; a document that embedded the WHOLE thing, or none of
    // it, lands outside this band.
    expect(bytes.length).toBeGreaterThan(20_000)
    expect(bytes.length).toBeLessThan(500_000)
  })

  it("omits the fingerprint line when the caller has none", async () => {
    const model = buildTranscriptModel({ holder: HOLDER, locale: "en", t, rows: ledger(2) })
    const withFp = await buildServiceHoursPdf({
      model,
      code: CODE,
      issuedAt: ISSUED_AT,
      fingerprint: "f".repeat(64),
      t,
    })
    const withoutFp = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    expect(withoutFp.length).toBeLessThan(withFp.length)
    expect(pageCount(withoutFp)).toBe(pageCount(withFp))
  })

  /**
   * `CreationDate`/`ModDate` are pinned to `issuedAt`, and the renderer takes no clock, so the
   * same snapshot must produce the same bytes. If this ever fails on a pdfkit upgrade: delete it, and
   * redefine `document_sha256` as "the hash of the bytes currently stored". Do not fight pdfkit.
   */
  it("is deterministic for a fixed snapshot, code and issue time", async () => {
    const model = buildTranscriptModel({ holder: HOLDER, locale: "en", t, rows: ledger(5) })
    const a = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    const b = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    expect(Buffer.from(a).equals(Buffer.from(b))).toBe(true)
  })

  it("mints different bytes for a different code", async () => {
    const model = buildTranscriptModel({ holder: HOLDER, locale: "en", t, rows: ledger(5) })
    const a = await buildServiceHoursPdf({ model, code: CODE, issuedAt: ISSUED_AT, t })
    const b = await buildServiceHoursPdf({ model, code: "Z9Y8X7W6V5T4", issuedAt: ISSUED_AT, t })
    expect(Buffer.from(a).equals(Buffer.from(b))).toBe(false)
  })
})

describe("fontFor", () => {
  it("keeps Latin (including accents) on the brand faces", () => {
    expect(fontFor("Jane Doe", "regular")).toBe(FONT.body)
    expect(fontFor("Jane Doe", "bold")).toBe(FONT.bodyBold)
    expect(fontFor("José Ramírez", "regular")).toBe(FONT.body)
    expect(fontFor("", "regular")).toBe(FONT.body)
  })

  it("switches the WHOLE string to Noto when any of it needs CJK", () => {
    expect(fontFor("홍길동", "regular")).toBe(FONT.cjk)
    // Per-string, not per-glyph: a mixed cell renders entirely in Noto, which has full Latin coverage.
    expect(fontFor("Cleanup at 강남구", "regular")).toBe(FONT.cjk)
    // Only the Regular CJK weight is vendored, so bold CJK falls back to it rather than to a Latin face.
    expect(fontFor("홍길동", "bold")).toBe(FONT.cjk)
  })
})
